AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  baleenn

  Sample SAM Template for baleenn

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  BaleennTestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/distributions/baleenn-app-1.0.0-SNAPSHOT.zip
      Handler: com.baleenn.lambda.LambdaTestHandler::handleRequest
      Runtime: java11
      MemorySize: 128
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BaleennTestFunction:
    Description: "Baleenn Test Lambda Function ARN"
    Value: !GetAtt BaleennTestFunction.Arn
  BaleennTestFunctionIamRole:
    Description: "Implicit IAM Role created for Baleenn Test Function"
    Value: !GetAtt BaleennTestFunctionRole.Arn
